services:
  web:
    image: odoo:17
    
    user: odoo 
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./volumesOdoo/addons:/mnt/extra-addons
      - ./volumesOdoo/odoo/filestore:/var/lib/odoo/filestore
      - ./volumesOdoo/odoo/sessions:/var/lib/odoo/sessions
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: --dev=all

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./volumesOdoo/dataPostgreSQL:/var/lib/postgresql/data